config/routes.rb
Forttree::Application.routes.draw do
  resources :boards do
    resources :posts, except: :destroy
  end

  delete '/boards/:board_id/posts', to: 'posts#destroy', as: 'posts_destroy'

  root :to => 'boards#index'
end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :branches
  has_attached_file :banner,
      :storage => STORAGE,
      :path => PHOTO_PATH,
      :s3_credentials => {
        :access_key_id => S3_KEY,
        :secret_access_key => S3_SECRET,
        :s3_region => S3_REGION
      },
      :bucket => S3_BUCKET
  default_scope -> { order('name ASC') }
  validates_attachment_content_type :banner, :content_type => VALID_ATTACHMENT_TYPES, :if => Proc.new { |p| p.errors.blank? }
  validates_attachment_size :banner, :less_than => MAX_UPLOAD_SIZE, :message => "File too big! :{", :if => Proc.new { |p| p.errors.blank? }
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :setup_negative_captcha, only: [:show]
  def index
    @latest_posts = Leaf.latest
  end
  def new
    @board = Board.new
  end
  def show
    @board = Board.find(params[:id])
    @post_form = PostForm.new @board
    @branches = @board.branches.page(params[:page])
    respond_to do |format|
      format.html
    end
  end
  def create
    @board = Board.new board_params
    respond_to do |format|
      if Admin.authenticate(params[:password])
        if @board.save!
          flash[:success] = "Board created!"
          format.html { redirect_to board_path @board }
        else
          flash[:error] = "Couldn't create board for some reason!"
          format.html { render action: 'new' }
        end
      else
          flash[:error] = "Incorrect password!"
          format.html { render action: 'new' }
      end
    end
  end
  def edit
    @board = Board.find(params[:id])
  end
  def update
    @board = Board.find(params[:id])

    respond_to do |format|
      if Admin.authenticate(params[:password])
        if @board.update_attributes! board_params
          flash[:success] = "Board updated!"
          format.html { redirect_to board_path @board }
        else
          flash[:error] = "Couldn't update board."
          format.html { render action: 'edit' }
        end
      else
        flash[:error] = "Incorrect password!"
          format.html { render action: 'edit' }
      end
    end
  end
  def destroy
    @board = Board.find(params[:id])

    respond_to do |format|
      if Admin.authenticate(params[:delete_password])
        if @board.destroy
          flash[:success] = "Board deleted!"
          format.html { redirect_to boards_path }
        else
          flash[:error] = "Couldnt delete board!"
          format.html { render action: 'edit' }
        end
      else
        flash[:error] = "Incorrect password!"
        format.html { render action: 'edit' }
      end
    end
  end

  private

  def board_params
    params.require(:board).permit(:name, :banner)
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_for @board, html: { multipart: true } do |f| %>
   <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%="Uh oh, you got" + pluralize(@board.errors.count, "error!")%></h2>
      <ul>
        <% @board.errors.full_messages.each do |msg| %>
          <li><%=msg%></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <tr>
      <td class="fieldlabel">Name</td>
      <td class="field"><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td class="fieldlabel">Banner</td>
      <td class="field"><%= f.file_field :banner %></td>
    </tr>
    <tr>
      <td class="fieldlabel">Password</td>
      <td class="field"><%= password_field_tag :password %>
    </tr>
  </table>  
  <%= f.submit value: 'Create board', id: 'submit' %>
<% end %>

app/views/boards/edit.html.erb
<h1>edit board</h1>
<%= render 'form' %>
<h2>DELETE BOARD</h2>
<p>can't be undone!</p>
<%= form_for @board, :html => {:method => :delete} do |f| %>
  <%= password_field_tag :delete_password %>
  <%= f.submit 'Delete board', id: 'delete' %>
<% end %>

app/views/boards/index.html.erb
<h2><%= t("latest_posts") %></h2>
<% @latest_posts.each do |post| %>
  <div class="forttree-box" style="animation: App-logo-spin infinite 20s linear;">
    <h3>in <%= link_to "/#{post.board_name}/", post.board %></h3>
    <%= link_to image_tag(post.photo.url(:thumb)), board_path(post.board) if post.photo.present? %>
    <blockquote>
      <%= display_content(post) %>
    </blockquote>
  </div>
<% end %>
<div style="clear: both;"></div>

app/views/boards/new.html.erb
<h1>New board</h1>
<%= render 'form' %>

app/views/boards/show.html.erb
  <center>
    <% if @board.banner %>
      <%= image_tag @board.banner.url, class: "forttree-banner" %>
    <% end %>
    <h2>/<%=@board.name%>/</h2>
  </center>
<div id="manage">
  <%= link_to "[Manage]", edit_board_path(@board) %>
</div>

<%= render :partial => "layouts/form", :locals => { :post_form => @post_form } %>

<%= form_for :post, url: posts_destroy_path(@post_form.board), :html => { :method => :delete } do |del| %>
  <div class="loader" style="display:none">
    <img src="/images/spinner.gif"/>
  </div>
  <div id="page">
    <div id="branches">
      <%= paginate @branches %>
      <%= render @branches, :action => :show %>
      <%= paginate @branches %>
    </div>
  </div>
  <div class="loader" style="display:none">
    <img src="/images/spinner.gif"/>
  </div>
  <table class="deleteform">
    <tbody>
      <tr>
        <td>
          <%= password_field_tag :password %>
          <%= del.submit(:class => 'submitbutton', :value => 'Delete') %>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>